language: go

go:
  - 1.9.x

go_import_path: k8s.io/kubectl

before_install:
  - source ./bin/consider-early-travis-exit.sh
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/monopole/mdrip

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
  -

script:
  - ./bin/pre-commit.sh

# TBD. Suppressing for now.
notifications:
  email: false
